### ISSUE TITLE
White screen after running app image

### ISSUE THREAD

**Issue by zono50** [smol-ai/GodMode#209]
Getting the following errors - 20:02:46.377 › Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.4/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.4/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Tue, 29 Aug 2023 00:02:17 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "A657:06B4:5A1D5B:7E778F:64ED35A6",
  "x-xss-protection": "0"
}
    at createHttpError (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at o.handleResponse (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49930)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
    at newError (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/index.js:47:19)
    at rawData (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/providers/GitHubProvider.js:108:54)
    at t.GitHubProvider.info [as getLatestVersion] (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/providers/GitHubProvider.js:120:17)
    at h.result [as getUpdateInfoAndProvider] (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/AppUpdater.js:319:13)
    at h.doCheckForUpdates (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/AppUpdater.js:333:15)
(node:38495) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.4/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.4/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Tue, 29 Aug 2023 00:02:17 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "A657:06B4:5A1D5B:7E778F:64ED35A6",
  "x-xss-protection": "0"
}
    at createHttpError (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at o.handleResponse (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49930)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
    at newError (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/index.js:47:19)
    at rawData (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/providers/GitHubProvider.js:108:54)
    at t.GitHubProvider.info [as getLatestVersion] (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/providers/GitHubProvider.js:120:17)
    at h.result [as getUpdateInfoAndProvider] (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/AppUpdater.js:319:13)
    at h.doCheckForUpdates (/tmp/.mount_GodModgKrZiG/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/AppUpdater.js:333:15)
(Use `godmode --trace-warnings ...` to show where the warning was created)
(node:38495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by swyxio** [comment]
no its not about downloading the file - when you boot up the app, it should check for the file on my hosted release instance, thats how it figures out if there has been an update. i've now uploaded the file.

**Comment by zono50** [comment]
still getting a white screen, getting the following error - true
14:43:41.456 › Checking for update
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
IPC test: ping
false
14:43:46.504 › Update for version 1.0.0-beta.5 is not available (latest version: 1.0.0-beta.5, downgrade is disallowed).
14:43:46.506 › checkForUpdatesAndNotify called, downloadPromise is null

**Comment by swyxio** [comment]
do you mind reading the errors a bit more and seeing what files it is looking for?

**Comment by zono50** [comment]
how do i do that? Any arguments I can pass to it?

**Comment by swyxio** [comment]
not that I'm aware unfortunately. cc @seanoliver in case you can think of something

**Comment by swyxio** [comment]
@zono50 we just pushed beta 6 today, lmk if still see same issues. still not sure how to debug.

**Comment by zono50** [comment]
Immediately updated, and immediately the same issue, weird thing tho version 3 works perfectly

**Comment by swyxio** [comment]
i'd like to enable a argument flag to open up devtools for you so that you can see if there are any errors, however i dont really know how to do it. if you've got the inclination, could use some help adding that in so that we can debug this and all future userland issues that I cant replicate. 

as for right now, you seem to be the only person reporting problems, so i'm wondering if it only affects linux users, or worse, linux arm64 users, in which case its probably that you are using the linux arm64 binary that i didnt continue uploading

**Comment by zono50** [comment]
I'm using the app image, but i'm open to any ideas

**Comment by zono50** [comment]
I may be wrong, but wondering if this is what's causing my white screen? libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

**Comment by swyxio** [comment]
yeah i have no idea what that is. could you doublecheck on a friend’s linux setup, or maybe build locally from scratch and enable devtools?

**Comment by zono50** [comment]
Tried to build it locally, but to no avail. I'll use version 3 for now. If we can figure out what changed from version 3 to version 6 that could be causing this, that would be cool

**Comment by swyxio** [comment]
ok. its more likely that beta 3 was missing the auto updating stuff which is why its not complaining.

i googled the error a bit and found [this](https://github.com/vector-im/element-web/issues/21805) but it wasnt in english. it looks to be a linux specific issue. this https://www.reddit.com/r/archlinux/comments/nl8e0y/google_chrome_libva_error/ and https://askubuntu.com/questions/1339829/chromium-core-dumped-libva-error-vagetdrivernamebyindex-failed-with-unknown had more potential for things to try. we could perhaps [disable gpu](https://stackoverflow.com/questions/71889868/google-chrome-gpu-error-in-electron-build) or [disable compositing](https://superuser.com/questions/1716854/disabling-gpu-compositing-for-all-chrome-and-electron-instances-on-a-mac) here for linux builds but i didnt do anything that funky in beta 3

**Comment by swyxio** [comment]
circling back to note that it was my turn to get the white screen when encountering beta 8. i need to figure out how to make this auto updater work.

**Comment by vibl** [comment]
I have the same problem on 1.0.0-beta.8: white screen a few seconds after starting, with the following logs:

``` 
IPC test: ping
false
20:38:05.871 › Update for version 1.0.0-beta.8 is not available (latest version: 1.0.0-beta.8, downgrade is disallowed).
20:38:05.872 › checkForUpdatesAndNotify called, downloadPromise is null

```

**Comment by kapitaali** [comment]
Getting this error with GodMode-1.0.0-beta.10.AppImage for Linux. It crashes the whole app and you're left with a white screen.

I'm running Pop!_OS 22.04 LTS x86_64 6.8.0-76060800daily20240311-generic #202403110203~1711393930~22.04~331756a SMP PREEMPT_DYNAMIC Mon M x86_64 x86_64 x86_64 GNU/Linux
