### ISSUE TITLE
White Screen When I open Godmode on MacBook Pro

### ISSUE THREAD

**Issue by agarwalprashant** [smol-ai/GodMode#266]
**Describe the bug**
I downloaded the GodMode app(GodMode-1.0.0-beta.9-universal.dmg) from GitHub onto my MacBook Pro (running macOS Ventura Version 13.6) and tried to open it. After allowing the app permission from my privacy settings in macOS, the app launched to a blank white screen and has remained like this. I have uninstalled and reinstalled the app, but the issue persists. Please let me know if you have a fix for this issue.
I was using the app without issue a few days ago, but then I toggled the visibility of two windows. Since then, the app's screen has been blank and white, and it has remained blank despite restarting the app and uninstalling/reinstalling it multiple times.

<img width="1658" alt="CleanShot 2023-10-28 at 14 52 34@2x" src="https://github.com/smol-ai/GodMode/assets/8237463/a74a3004-f40d-4275-9a5b-2230a8b6de37">

**To Reproduce**
Please toggle the visibility of the chatgpt and claude windows to "none" to hide them from view. Doing so will bring up a blank window that will remain onscreen indefinitely. Thank you.

**Expected behavior**
App should work fine and I should get the option to select the windows.

**Screenshots**
<img width="1658" alt="CleanShot 2023-10-28 at 14 52 34@2x" src="https://github.com/smol-ai/GodMode/assets/8237463/a74a3004-f40d-4275-9a5b-2230a8b6de37">

**Desktop (please complete the following information):**

- OS:  macOS Ventura Version 13.6
- GodMode Version - GodMode-1.0.0-beta.9-universal

**Additional context**

**Comment by agarwalprashant** [comment]
Is there a solution to this problem?

**Comment by swyxio** [comment]
thanks very much for this extensive report! I dont have a solution for this right now as i dont know how to reproduce this. welcome to people to investigate this as i suspect it is a bug with Electron and the automated updater process.

**Comment by coltbleu** [comment]
I have the same issues with the white screen. Have tried removing the application and installing it again with no luck

**Comment by agarwalprashant** [comment]
Even after uninstalling and then reinstalling the app, the white screen issue persists.

**Comment by coltbleu** [comment]
Yes it still persists even after un installing / reinstalling. Very strange. When I first installed the application worked great. Maybe a recent OS update affected it?

**Comment by swyxio** [comment]
i dont know the cause still as it doesnt occur on my machine

**Comment by developerisnow** [comment]
Does anybody solved it on mac m1 ? The same problem

**Comment by flavioislima** [comment]
I can replicate this on Linux using the AppImage. 

@swyxio  I believe that the issue is because the Electron updater cannot find a latest-linux.yml file on github so it fails to check if there is a new version for the app.

Perhaps just adding a try/catch surrounding the method that checks for the update could work. It is just an unhandled promise.

**Comment by flavioislima** [comment]
This is what shows when I open it from the terminal:
```

./GodMode-1.0.0-beta.10.AppImage
CommandOrControl+Shift+G
true
focus superprompt enabled false
20:11:35.586 › Checking for update
IPC test: ping
false
20:11:36.566 › Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.10/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.10/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Mon, 01 Jan 2024 20:11:05 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "BC30:1CAF9F:FC1356E:FF81454:65931C78",
  "x-xss-protection": "0"
}
    at createHttpError (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at a.handleResponse (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49930)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
    at newError (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/index.js:47:19)
    at rawData (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/providers/GitHubProvider.js:108:54)
    at t.GitHubProvider.info [as getLatestVersion] (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/providers/GitHubProvider.js:120:17)
    at d.result [as getUpdateInfoAndProvider] (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/AppUpdater.js:319:13)
    at doCheckForUpdates (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/AppUpdater.js:333:15)
(node:81147) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.10/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.10/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Mon, 01 Jan 2024 20:11:05 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "BC30:1CAF9F:FC1356E:FF81454:65931C78",
  "x-xss-protection": "0"
}
    at createHttpError (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at a.handleResponse (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49930)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
    at newError (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/builder-util-runtime/out/index.js:47:19)
    at rawData (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/providers/GitHubProvider.js:108:54)
    at t.GitHubProvider.info [as getLatestVersion] (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/providers/GitHubProvider.js:120:17)
    at d.result [as getUpdateInfoAndProvider] (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/AppUpdater.js:319:13)
    at doCheckForUpdates (/tmp/.mount_GodModyEezEw/resources/app.asar/dist/main/webpack:/godmode/node_modules/electron-updater/out/AppUpdater.js:333:15)
(Use `godmode --trace-warnings ...` to show where the warning was created)
(node:81147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[81181:0101/201141.490783:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
^C%                                                                                                             
```

**Comment by HunterGerlach** [comment]
I think the latest-linux.yml is a red herring. Simply updating the packages will pull in the necessary bug fixes to overcome this issue.

**Comment by mikZybien** [comment]
hello guys can you help me how to hack facebook account of a criminal?

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Nov 9, 2023 at 11:12 AM, Prashant ***@***.***> wrote:   


Is there a solution to this problem?

**Comment by mikZybien** [comment]
guys 
hello can i report the facebook account of Darwin Aminoso coz his posting inappropriate things..violence agaisnt facebook its a cyber libel
Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, Nov 17, 2023 at 5:36 AM, ***@***.***> wrote:   


thanks very much for this extensive report! I dont have a solution for this right now as i dont know how to reproduce this. welcome to people to investigate this as i suspect it is a bug with Electron and the automated updater process.
